### ISSUE TITLE
Update vignette

### ISSUE THREAD

**Issue by zenalapp** [Snitkin-Lab-Umich/regentrans#43]
- [x] Add link to good review: https://pubmed.ncbi.nlm.nih.gov/28513284/
- [x] Add tree building recommendations
- [x] Code to bin `get_frac_intra()` output (data frame and plot) 
- [x] Fix environmental sample example (#42)
- [x] Add code to assign each isolate to a cluster based on the `get_clusters` output (maybe include as package function instead?) (#19)
- [x] Update vignette to show manuscript figures (#27)
- [x] Update text to flow based on updates described above
- [x] Explain how to make get_clusters run faster using a parallelization scheme
- [x] Add pre-processing figure to vignette
- [x] Organize files to not get notes in `devtools::check()`
- [ ] Check link to vignette on GitHub and change if broken
